# Generated by Django 6.0.1 on 2026-01-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('DEJEUNERS', 'Déjeuners'), ('RESTAURANT', 'Restaurant'), ('CAFETERIA', 'Cafétéria'), ('GYMNASE', 'Gymnase'), ('AMPHI_DASSAULT', 'Amphithéâtre M. Dassault'), ('EPI5', 'Epi 5'), ('AMPHI', 'Amphi'), ('ACCUEIL', 'Accueil'), ('EPI2', 'Epi 2'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('POSTE_NORD', 'Poste Nord'), ('PORTE_NORD', 'Porte Nord'), ('ROND_POINT', 'Rond-Point'), ('PORTE_PRINCIPALE', 'Porte principale')], max_length=50, verbose_name='Lieu'),
        ),
    ]
