# Generated by Django 5.2.7 on 2026-03-08 13:21

from django.db import migrations, models


def migrate_locations_to_new_codes(apps, schema_editor):
    Event = apps.get_model('events', 'Event')

    code_map = {
        'DEJEUNERS': 'RESTAURANT_CROUS',
        'RESTAURANT': 'RESTAURANT_CROUS',
        'CAFETERIA': 'CAFETERIA',
        'GYMNASE': 'GYMNASE',
        'AMPHI_DASSAULT': 'AMPHI_2',
        'EPI5': 'EPI_5',
        'AMPHI': 'AMPHI_1',
        'ACCUEIL': 'ACCUEIL',
        'EPI2': 'EPI_2',
        'BIBLIOTHEQUE': 'BIBLIOTHEQUE',
        'POSTE_NORD': 'ACCUEIL',
        'PORTE_NORD': 'ACCUEIL',
        'ROND_POINT': 'ACCUEIL',
        'PORTE_PRINCIPALE': 'ACCUEIL',
        'EXPOSES': 'EPI_3',
    }

    valid_new_codes = {
        'EPI_1',
        'EPI_2',
        'EPI_3',
        'EPI_4',
        'EPI_5',
        'EPI_6',
        'AMPHI_1',
        'AMPHI_2',
        'AMPHI_3',
        'AMPHI_4',
        'ACCUEIL',
        'BIBLIOTHEQUE',
        'RESTAURANT_CROUS',
        'CAFETERIA',
        'GYMNASE',
    }

    for event in Event.objects.all().only('id', 'location'):
        old_code = event.location
        if old_code in valid_new_codes:
            continue
        event.location = code_map.get(old_code, 'ACCUEIL')
        event.save(update_fields=['location'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_location'),
    ]

    operations = [
        migrations.RunPython(
            migrate_locations_to_new_codes,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('EPI_1', 'Epi 1'), ('EPI_2', 'Epi 2'), ('EPI_3', 'Epi 3'), ('EPI_4', 'Epi 4'), ('EPI_5', 'Epi 5'), ('EPI_6', 'Epi 6'), ('AMPHI_1', 'Amphi 1'), ('AMPHI_2', 'Amphi 2'), ('AMPHI_3', 'Amphi 3'), ('AMPHI_4', 'Amphi 4'), ('ACCUEIL', 'Accueil'), ('BIBLIOTHEQUE', 'Bibliotheque'), ('RESTAURANT_CROUS', 'Restaurant Crous'), ('CAFETERIA', 'Cafeteria'), ('GYMNASE', 'Gymnase')], max_length=50, verbose_name='Lieu'),
        ),
    ]
