# Generated by Django 5.2.7 on 2026-03-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('EPI_1', 'Epi 1'), ('EPI_2', 'Epi 2'), ('EPI_3', 'Epi 3'), ('EPI_4', 'Epi 4'), ('EPI_5', 'Epi 5'), ('EPI_6', 'Epi 6'), ('AMPHI_1', 'Amphi 1'), ('AMPHI_2', 'Amphi 2'), ('AMPHI_3', 'Amphi 3'), ('AMPHI_4', 'Amphi 4'), ('ACCUEIL', 'Accueil'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('RESTAURANT_CROUS', 'Restaurant Crous'), ('CAFETERIA', 'Cafétéria'), ('GYMNASE', 'Gymnase')], max_length=50, verbose_name='Lieu'),
        ),
    ]
