# Generated by Django 5.2.7 on 2026-03-08 13:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


LOCATION_SEED = [
    {"slug": "epi-1", "name": "Epi 1", "x": "56.00", "y": "28.00"},
    {"slug": "epi-2", "name": "Epi 2", "x": "60.00", "y": "31.00"},
    {"slug": "epi-3", "name": "Epi 3", "x": "64.00", "y": "27.00"},
    {"slug": "epi-4", "name": "Epi 4", "x": "67.00", "y": "24.00"},
    {"slug": "epi-5", "name": "Epi 5", "x": "34.00", "y": "25.00"},
    {"slug": "epi-6", "name": "Epi 6", "x": "37.00", "y": "40.00"},
    {"slug": "amphi-1", "name": "Amphi 1", "x": "45.00", "y": "32.00"},
    {"slug": "amphi-2", "name": "Amphi 2", "x": "25.00", "y": "34.00"},
    {"slug": "amphi-3", "name": "Amphi 3", "x": "42.00", "y": "29.00"},
    {"slug": "amphi-4", "name": "Amphi 4", "x": "48.00", "y": "36.00"},
    {"slug": "accueil", "name": "Accueil", "x": "50.00", "y": "22.00"},
    {"slug": "bibliotheque", "name": "Biblioth\u00e8que", "x": "68.00", "y": "39.00"},
    {"slug": "restaurant-crous", "name": "Restaurant Crous", "x": "10.00", "y": "34.00"},
    {"slug": "cafeteria", "name": "Caf\u00e9t\u00e9ria", "x": "12.00", "y": "27.00"},
    {"slug": "gymnase", "name": "Gymnase", "x": "11.00", "y": "12.00"},
]


def forward_seed_locations_and_map_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Location = apps.get_model("events", "Location")

    slug_to_location = {}
    for data in LOCATION_SEED:
        location, _ = Location.objects.update_or_create(
            slug=data["slug"],
            defaults={
                "name": data["name"],
                "x_percent": data["x"],
                "y_percent": data["y"],
            },
        )
        slug_to_location[data["slug"]] = location

    code_to_slug = {
        # New standardized codes
        "EPI_1": "epi-1",
        "EPI_2": "epi-2",
        "EPI_3": "epi-3",
        "EPI_4": "epi-4",
        "EPI_5": "epi-5",
        "EPI_6": "epi-6",
        "AMPHI_1": "amphi-1",
        "AMPHI_2": "amphi-2",
        "AMPHI_3": "amphi-3",
        "AMPHI_4": "amphi-4",
        "ACCUEIL": "accueil",
        "BIBLIOTHEQUE": "bibliotheque",
        "RESTAURANT_CROUS": "restaurant-crous",
        "CAFETERIA": "cafeteria",
        "GYMNASE": "gymnase",

        # Legacy codes kept for compatibility
        "DEJEUNERS": "restaurant-crous",
        "RESTAURANT": "restaurant-crous",
        "AMPHI_DASSAULT": "amphi-2",
        "EPI5": "epi-5",
        "AMPHI": "amphi-1",
        "EPI2": "epi-2",
        "POSTE_NORD": "accueil",
        "PORTE_NORD": "accueil",
        "ROND_POINT": "accueil",
        "PORTE_PRINCIPALE": "accueil",
        "EXPOSES": "epi-3",
    }

    fallback = slug_to_location["accueil"]

    for event in Event.objects.all().only("id", "location"):
        mapped_slug = code_to_slug.get(event.location, "accueil")
        event.location_new_id = slug_to_location.get(mapped_slug, fallback).id
        event.save(update_fields=["location_new"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "x_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "y_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="event",
            name="location_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events_tmp",
                to="events.location",
                verbose_name="Lieu",
            ),
        ),
        migrations.RunPython(
            forward_seed_locations_and_map_events,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="location_new",
            new_name="location",
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="events.location",
                verbose_name="Lieu",
            ),
        ),
    ]
