# Generated by Django 5.2.7 on 2026-03-08 13:49

from django.db import migrations


def tune_location_coordinates(apps, schema_editor):
    Location = apps.get_model("events", "Location")

    coords = {
        "epi-1": ("56.00", "28.00"),
        "epi-2": ("60.00", "31.00"),
        "epi-3": ("64.00", "27.00"),
        "epi-4": ("67.00", "24.00"),
        "epi-5": ("34.00", "25.00"),
        "epi-6": ("37.00", "40.00"),
        "amphi-1": ("45.00", "32.00"),
        "amphi-2": ("25.00", "34.00"),
        "amphi-3": ("42.00", "29.00"),
        "amphi-4": ("48.00", "36.00"),
        "accueil": ("50.00", "22.00"),
        "bibliotheque": ("68.00", "39.00"),
        "restaurant-crous": ("18.00", "34.00"),
        "cafeteria": ("12.00", "27.00"),
        "gymnase": ("11.00", "12.00"),
    }

    for slug, (x_percent, y_percent) in coords.items():
        Location.objects.filter(slug=slug).update(
            x_percent=x_percent,
            y_percent=y_percent,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_location_alter_event_location'),
    ]

    operations = [
        migrations.RunPython(tune_location_coordinates, migrations.RunPython.noop),
    ]
