# Generated by Django 5.2.7 on 2026-03-08 22:57

from django.db import migrations


def align_locations_to_map_points(apps, schema_editor):
    Location = apps.get_model("events", "Location")

    # Coordinates aligned on the existing pink points drawn on the ESIEE map image.
    coords = {
        "gymnase": ("11.00", "12.00"),
        "restaurant-crous": ("10.00", "34.00"),
        "cafeteria": ("12.00", "27.00"),
        "amphi-2": ("25.00", "34.00"),
        "epi-5": ("34.00", "25.00"),
        "epi-6": ("37.00", "40.00"),
        "amphi-1": ("45.00", "32.00"),
        "accueil": ("50.00", "22.00"),
        "amphi-3": ("50.00", "41.00"),
        "epi-2": ("60.00", "31.00"),
        "bibliotheque": ("68.00", "39.00"),
        "epi-1": ("73.00", "47.00"),
        "epi-3": ("82.00", "30.00"),
        "epi-4": ("88.00", "22.00"),
        "amphi-4": ("90.00", "40.00"),
    }

    for slug, (x_percent, y_percent) in coords.items():
        Location.objects.filter(slug=slug).update(
            x_percent=x_percent,
            y_percent=y_percent,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_tune_location_coordinates'),
    ]

    operations = [
        migrations.RunPython(align_locations_to_map_points, migrations.RunPython.noop),
    ]
