# Generated by Codex on 2026-03-09

from django.db import migrations


def recalibrate_locations(apps, schema_editor):
    Location = apps.get_model("events", "Location")

    coords = {
        "epi-6": ("38.78", "23.18"),
        "epi-5": ("48.78", "22.91"),
        "epi-4": ("58.67", "22.39"),
        "epi-3": ("69.22", "22.91"),
        "epi-2": ("79.22", "22.91"),
        "epi-1": ("89.89", "23.18"),
        "cafeteria": ("29.56", "51.82"),
        "restaurant-crous": ("18.22", "72.57"),
        "accueil": ("58.22", "50.76"),
        "bibliotheque": ("89.00", "63.38"),
        "amphi-3": ("50.33", "53.39"),
        "amphi-4": ("50.33", "53.39"),
        "amphi-1": ("77.78", "54.18"),
        "amphi-2": ("77.78", "54.18"),
        "gymnase": ("14.22", "18.97"),
    }

    for slug, (x_percent, y_percent) in coords.items():
        Location.objects.filter(slug=slug).update(
            x_percent=x_percent,
            y_percent=y_percent,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_align_locations_to_map_points"),
    ]

    operations = [
        migrations.RunPython(recalibrate_locations, migrations.RunPython.noop),
    ]
